# Generated by Django 5.1.3 on 2024-11-13 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldmineCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VinylRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_code', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('album_name', models.CharField(max_length=128)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=64)),
                ('location', models.JSONField()),
                ('available_for_exchange', models.BooleanField()),
                ('additional_description', models.CharField(max_length=256)),
                ('cover_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_condition', to='api.goldminecondition')),
                ('record_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_condition', to='api.goldminecondition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_content', models.BinaryField()),
                ('vinyl_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vinylrecord')),
            ],
        ),
    ]
